version: '3.8'

services:
  genah-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genah-express
    ports:
      - "3034:80"
    env_file:
      - .env
    restart: unless-stopped